% 1: Write a DCG that generates and analyses all meaningful sentences using the following words:
% the shark, the goldfish, the eagle, the finch, the boy, eats, swims, flies, drowns.
% "Meaningful" means that sharks don't fly and herbivores don't eat other beings etc., i.e. the shark flies should not be generated by your grammar. Similarly finches are not carnivore, mammals can swim but birds can't etc.
% Hints: - Treat 'the shark' as one word, i.e. n --> ['the shark'] etc.
%        - Classify the words and use your classes as node labels.
%        - Don't bother with Chomsky Normal Form or other fancy things.
%        - Mind that drowning and eating can but not necessarily do take an object.
%
% 2. On an ancient scroll written in an even more ancient language called 'Pthu' the following sentences were found:
%
%    Nqblubh Mhboa.
%    Nqrrroah Ukahama Nqblubh.
%    Nqlhalha Falup.
%    Nqlhalha Ukahama.
%    Nqlhalha Ukahama Nqflua.
%    Nqflua Sharabrab.
%    Nqblubh Falup Nqdwingi.
%    Nqflua Ukahama Nqdwingi.
%    Nqdwingi Falup Nqflua.
%
% Assume the syntactic structure of Pthu is the same as it is in english.
% Use the grammar from the previous task to give a english translation for every word of the scroll.
%
% Hint: Again, 'the shark' will be a single word in Pthu. Instantiate every Pthu word with an english word and check if all the so-translated sentences are meaningful. You may use built-in predicates for list processing. If you don't get a unique solution or no solution it all it might be because your grammar generates a set of sentences different to the intended one. There should be 43 sentences generated by your grammar.
%
% translation(Nqrrroah, Nqblubh, Nqflua, Nqdwingi, Nqlhalha, Ukahama, Mhboa, Sharabrab, Falup) :-
%    ...
